// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantManager.Data;

#nullable disable

namespace RestaurantManager.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260721140936_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RestaurantManager.Models.BanAn", b =>
                {
                    b.Property<int>("MaBan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBan"));

                    b.Property<string>("KhuVuc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SoCho")
                        .HasColumnType("int");

                    b.Property<string>("TenBan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaBan");

                    b.HasIndex("TenBan")
                        .IsUnique();

                    b.ToTable("BanAn", null, t =>
                        {
                            t.HasCheckConstraint("CK_BanAn_SoCho", "[SoCho] > 0");
                        });
                });

            modelBuilder.Entity("RestaurantManager.Models.ChiTietDonGoiMon", b =>
                {
                    b.Property<int>("MaChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTiet"));

                    b.Property<decimal>("DonGia")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaDon")
                        .HasColumnType("int");

                    b.Property<int>("MaMon")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal>("ThanhTien")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThaiMon")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaChiTiet");

                    b.HasIndex("MaMon");

                    b.HasIndex("MaDon", "MaMon");

                    b.ToTable("ChiTietDonGoiMon", null, t =>
                        {
                            t.HasCheckConstraint("CK_ChiTietDon_DonGia", "[DonGia] > 0");

                            t.HasCheckConstraint("CK_ChiTietDon_SoLuong", "[SoLuong] > 0");

                            t.HasCheckConstraint("CK_ChiTietDon_ThanhTien", "[ThanhTien] >= 0");
                        });
                });

            modelBuilder.Entity("RestaurantManager.Models.DanhMucMonAn", b =>
                {
                    b.Property<int>("MaDanhMuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhMuc"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaDanhMuc");

                    b.HasIndex("TenDanhMuc")
                        .IsUnique();

                    b.ToTable("DanhMucMonAn", (string)null);
                });

            modelBuilder.Entity("RestaurantManager.Models.DatBan", b =>
                {
                    b.Property<int>("MaDatBan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDatBan"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MaBan")
                        .HasColumnType("int");

                    b.Property<int>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<int>("SoNguoi")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaDatBan");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaBan", "ThoiGianBatDau", "ThoiGianKetThuc");

                    b.ToTable("DatBan", null, t =>
                        {
                            t.HasCheckConstraint("CK_DatBan_SoNguoi", "[SoNguoi] > 0");

                            t.HasCheckConstraint("CK_DatBan_ThoiGian", "[ThoiGianKetThuc] > [ThoiGianBatDau]");
                        });
                });

            modelBuilder.Entity("RestaurantManager.Models.DonGoiMon", b =>
                {
                    b.Property<int>("MaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDon"));

                    b.Property<int>("MaBan")
                        .HasColumnType("int");

                    b.Property<int?>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaDon");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaNhanVien");

                    b.HasIndex("MaBan", "TrangThai");

                    b.ToTable("DonGoiMon", (string)null);
                });

            modelBuilder.Entity("RestaurantManager.Models.HoaDon", b =>
                {
                    b.Property<int>("MaHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHoaDon"));

                    b.Property<decimal>("GiamGia")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaDon")
                        .HasColumnType("int");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhuongThuc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("ThanhTien")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongTien")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaHoaDon");

                    b.HasIndex("MaDon")
                        .IsUnique();

                    b.HasIndex("MaNhanVien");

                    b.HasIndex("NgayThanhToan");

                    b.ToTable("HoaDon", null, t =>
                        {
                            t.HasCheckConstraint("CK_HoaDon_GiamGia", "[GiamGia] >= 0 AND [GiamGia] <= [TongTien]");

                            t.HasCheckConstraint("CK_HoaDon_ThanhTien", "[ThanhTien] >= 0");

                            t.HasCheckConstraint("CK_HoaDon_TongTien", "[TongTien] >= 0");
                        });
                });

            modelBuilder.Entity("RestaurantManager.Models.KhachHang", b =>
                {
                    b.Property<int>("MaKhachHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhachHang"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("MaKhachHang");

                    b.HasIndex("SoDienThoai");

                    b.ToTable("KhachHang", null, t =>
                        {
                            t.HasCheckConstraint("CK_KhachHang_SoDienThoai", "LEN([SoDienThoai]) BETWEEN 9 AND 15");
                        });
                });

            modelBuilder.Entity("RestaurantManager.Models.MonAn", b =>
                {
                    b.Property<int>("MaMon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaMon"));

                    b.Property<decimal>("DonGia")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MaDanhMuc")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TenMon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaMon");

                    b.HasIndex("MaDanhMuc", "TenMon");

                    b.ToTable("MonAn", null, t =>
                        {
                            t.HasCheckConstraint("CK_MonAn_DonGia", "[DonGia] > 0");
                        });
                });

            modelBuilder.Entity("RestaurantManager.Models.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiDung"));

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaVaiTro")
                        .HasColumnType("int");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaNguoiDung");

                    b.HasIndex("MaVaiTro");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("RestaurantManager.Models.VaiTro", b =>
                {
                    b.Property<int>("MaVaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaVaiTro"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaVaiTro");

                    b.HasIndex("TenVaiTro")
                        .IsUnique();

                    b.ToTable("VaiTro", (string)null);
                });

            modelBuilder.Entity("RestaurantManager.Models.ChiTietDonGoiMon", b =>
                {
                    b.HasOne("RestaurantManager.Models.DonGoiMon", "DonGoiMon")
                        .WithMany("ChiTietDonGoiMons")
                        .HasForeignKey("MaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestaurantManager.Models.MonAn", "MonAn")
                        .WithMany("ChiTietDonGoiMons")
                        .HasForeignKey("MaMon")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DonGoiMon");

                    b.Navigation("MonAn");
                });

            modelBuilder.Entity("RestaurantManager.Models.DatBan", b =>
                {
                    b.HasOne("RestaurantManager.Models.BanAn", "BanAn")
                        .WithMany("DatBans")
                        .HasForeignKey("MaBan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RestaurantManager.Models.KhachHang", "KhachHang")
                        .WithMany("DatBans")
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BanAn");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("RestaurantManager.Models.DonGoiMon", b =>
                {
                    b.HasOne("RestaurantManager.Models.BanAn", "BanAn")
                        .WithMany("DonGoiMons")
                        .HasForeignKey("MaBan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RestaurantManager.Models.KhachHang", "KhachHang")
                        .WithMany("DonGoiMons")
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RestaurantManager.Models.NguoiDung", "NhanVien")
                        .WithMany("DonGoiMons")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BanAn");

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("RestaurantManager.Models.HoaDon", b =>
                {
                    b.HasOne("RestaurantManager.Models.DonGoiMon", "DonGoiMon")
                        .WithOne("HoaDon")
                        .HasForeignKey("RestaurantManager.Models.HoaDon", "MaDon")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RestaurantManager.Models.NguoiDung", "NhanVien")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DonGoiMon");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("RestaurantManager.Models.MonAn", b =>
                {
                    b.HasOne("RestaurantManager.Models.DanhMucMonAn", "DanhMucMonAn")
                        .WithMany("MonAns")
                        .HasForeignKey("MaDanhMuc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DanhMucMonAn");
                });

            modelBuilder.Entity("RestaurantManager.Models.NguoiDung", b =>
                {
                    b.HasOne("RestaurantManager.Models.VaiTro", "VaiTro")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("MaVaiTro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("RestaurantManager.Models.BanAn", b =>
                {
                    b.Navigation("DatBans");

                    b.Navigation("DonGoiMons");
                });

            modelBuilder.Entity("RestaurantManager.Models.DanhMucMonAn", b =>
                {
                    b.Navigation("MonAns");
                });

            modelBuilder.Entity("RestaurantManager.Models.DonGoiMon", b =>
                {
                    b.Navigation("ChiTietDonGoiMons");

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("RestaurantManager.Models.KhachHang", b =>
                {
                    b.Navigation("DatBans");

                    b.Navigation("DonGoiMons");
                });

            modelBuilder.Entity("RestaurantManager.Models.MonAn", b =>
                {
                    b.Navigation("ChiTietDonGoiMons");
                });

            modelBuilder.Entity("RestaurantManager.Models.NguoiDung", b =>
                {
                    b.Navigation("DonGoiMons");

                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("RestaurantManager.Models.VaiTro", b =>
                {
                    b.Navigation("NguoiDungs");
                });
#pragma warning restore 612, 618
        }
    }
}
